ALTER TABLE products ADD COLUMN IF NOT EXISTS slug TEXT;

-- Existing products get a slug from their title; later ones are generated by the API.
UPDATE products
SET slug = CASE WHEN ranked.number = 1 THEN ranked.base ELSE ranked.base || '-' || ranked.number END
FROM (
  SELECT id, base, row_number() OVER (PARTITION BY base ORDER BY id) AS number
  FROM (
    SELECT id, COALESCE(NULLIF(trim(BOTH '-' FROM regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g')), ''), 'product') AS base
    FROM products
    WHERE slug IS NULL
  ) AS bases
) AS ranked
WHERE products.id = ranked.id;

ALTER TABLE products ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS products_slug_key ON products (slug);
